# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=210)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='profile_images')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='*First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='*Last name')),
                ('patronymic', models.CharField(max_length=50, verbose_name='*Patronymic')),
                ('email', models.EmailField(max_length=50, verbose_name='*E-mail')),
                ('home', models.CharField(max_length=50, verbose_name='*Home')),
                ('apartment', models.CharField(max_length=50, verbose_name='*Apartment')),
                ('password', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=50, verbose_name='*Contract')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
