# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190527_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='*First nameg'),
        ),
    ]
