# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190527_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Profile'),
        ),
    ]
