# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190527_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='contract',
            new_name='client',
        ),
    ]
