# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190527_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
