# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_documents_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='client',
        ),
        migrations.AddField(
            model_name='documents',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Contract'),
            preserve_default=False,
        ),
    ]
